config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'ideas#index'

  devise_for :users

  resources :ideas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :description, length: { minimum: 10 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :rememberable, :trackable,
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  has_many :ideas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  before_action :set_idea, only: [:edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound do |e|
    redirect_to ideas_path, alert: 'There is no such idea or you have no permissions to do that'
  end

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = current_user.ideas.build(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = current_user.ideas.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :idea_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :idea_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>By</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.user.email %></td>
        <td><%= idea.description %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>By:</strong>
  <%= @idea.user.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Ideas', ideas_path %> |
    Welcome
    <% if current_user %>
      <%= current_user.email %>
      <%= link_to 'Logout', destroy_user_session_path %>
    <% else %>
      Guest
      <%= link_to 'Login', new_user_session_path %>
      <%= link_to 'Signup', new_user_registration_path %>
    <% end %>
    <hr/>
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>